### PR TITLE
Added terminal app detection.

### LINKED ISSUE #21: iTerm2 support
I'm currently using [iTerm2](https://www.iterm2.com/) rather than terminal and both the `activateTerminalOnError` and `onClick` opens a new Terminal (not ideal).

So two questions:

- Can iTerm2 be supported by default? And, if not,
- What's the quickest path to me solving this in my own project (ie is there a parameter for which application gets opened that I can change)?

### PR DESCRIPTION
**Pull request by blvz**
Fixes #21.

### CODE REVIEW

**Comment by blvz** [comment]
@saiichihashimoto This activates the app that started the process, so it works even if you have one instance running on Terminal and another on iTerm.

**Comment by saiichihashimoto** [comment]
I Love it! Let's get this baby merged!!!!

**Comment by saiichihashimoto** [comment]
What's the releases like @RoccoC? ie, when can I expect this to be in npm?

**Comment by RoccoC** [comment]
@saiichihashimoto , v0.1.22 is now published to NPM.

**Pull request merged**
