### PR TITLE
Made notifier call notify async

### PR DESCRIPTION
**Pull request by quintonn**
Changed the call to notifier.notify async using setTimeout so it doesn't block the build, and also set wait to false

### CODE REVIEW

**Comment by RoccoC** [comment]
Thanks for the PR. Will review over the next couple of days.

**Comment by RoccoC** [comment]
I've merged this into a new branch, `bugfix/blocking-notifications` so I can do some manual testing before reintegrating into `master`. Will update here shortly with my findings. Thanks!

**Comment by RoccoC** [comment]
Hmm, in my testing it seems that while the notification is now shown consistently in Windows (due to setting `wait` to `true`, the build is still blocked until the notification is dismissed. I wonder if we could instead fork a detached process to dispatch the notification? I'll try and think of other solutions, open to any suggestions as well. :)

**Comment by quintonn** [comment]
How do you go about testing it?
I am using webpack in watch mode (-w) and my builds are succeeding as i never dismiss the notification.
Maybe i've done something different

**Comment by RoccoC** [comment]
If you run *without* watch mode, you should see that the build completes only once the notification has been dismissed.

**Comment by quintonn** [comment]
It seems you're right.
But the notification dismisses itself after a few seconds and then the build is done. but i guess that's not a good solution.
Guess we need to wait for node-notifier to fix the issue.

**Pull request merged**
